### ISSUE TITLE
Fatal error randomly in combining Starting_Items+New_Spawn_Tele

### ISSUE THREAD

**Issue by aksrz** [dmustanger/7dtd-ServerTools#440]
2023-05-09T19:20:11 8345.762 INF PlayerSpawnedInWorld (reason: Teleport, position: -2506, 129, -143): EntityID=xxxxxxx, PltfmId='Steam_xxxxxxxxxxxxxxxxxxxxx', CrossId='EOS_xxxxxxxxxxxxxxxxxxxxxxxxxxxx', OwnerID='Steam_xxxxxxxxxxxxxxxxxxxxx', PlayerName='xxxxxxxx'
2023-05-09T19:20:12 8346.611 INF [SERVERTOOLS] Player named 'xxxxxxxx' with Id 'Steam_xxxxxxxxxxxxxxxxxxxxx' 'EOS_xxxxxxxxxxxxxxxxxxxxxxxxxxxx' received their starting items
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Obtained 10 stack frames.
#0  0x007fc063469140 in funlockfile
#1  0x007fc0640e9100 in GameObject::QueryComponentByType(Unity::Type const*) const
#2  0x007fc0643fcc94 in PhysicsManager::SyncTransforms()
#3  0x007fc0643fcfb2 in PhysicsManager::ResetInterpolatedTransformPosition()
#4  0x007fc064317ca7 in ExecutePlayerLoop(NativePlayerLoopSystem*)
#5  0x007fc064317c62 in ExecutePlayerLoop(NativePlayerLoopSystem*)
#6  0x007fc06431820e in PlayerLoop()
#7  0x007fc0644f5af6 in PlayerMain(int, char**)
#8  0x007fc0632a4d0a in __libc_start_main
#9  0x00555f5f93f029 in _start

**Comment by ObsComp** [comment]
It's possible I need to put a timer on the initial spawning of the items given to the player. Giving them more time to finish spawning in. I will mark it down
